### ISSUE TITLE
New AWS YML configuration leads to rails & mongo throttling issues

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#448]
### General Issue / Feature Information

**Description**

In modest-scale analyses on AWS (~150 cores in the cluster) the web gui becomes unavailable, and mongo requests time out frequently after ~30 minutes. 

**Reproduction steps:**
1. Run a project that will keep several worker nodes busy for more than an hour
2. Wait 20 minutes
3. Refresh the web gui

**Actual outcome:**
Timeout error

**Expected outcome:**
Webpage loads

### Error on Remote Server Details

**AMI version being used**

2.7.0

**Server management log file**

Not useful in this case - instead refer to this [commit](https://github.com/NREL/OpenStudio-server/commit/e580bd413da02e3c5d8ee1f91383bdd0a9afcd26#diff-faf230be006717d296d00f2c4b3fce43) and the screenshot from @ejhw that will be attached momentarily from the server node. You will see more than 4 oscli / E+ threads, even though 12 cores should be reserved for use by the non-worker containers.

**Comment by ejhw** [comment]
![image](https://user-images.githubusercontent.com/1276021/49837161-ae700780-fd62-11e8-944e-8458cd15c8e0.png)

**Comment by ejhw** [comment]
```
version: '3'
services:
  db:
    image: localhost:5000/mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "3"
  queue:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
  web:
    image: localhost:5000/openstudio-server
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=134
      - MAX_REQUESTS=180
      - MAX_POOL=80
      - QUEUES=analysis_wrappers
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - queue
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "5"
    command: /usr/local/bin/start-server
  web-background:
    image: localhost:5000/openstudio-server
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=134
      - QUEUES=background,analyses
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - web
      - queue
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
    command: /usr/local/bin/start-web-background
  worker:
    image: localhost:5000/openstudio-server
    environment:
      - QUEUES=simulations
      - COUNT=1
    volumes:
      - /mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
      - queue
      - rserve
    deploy:
      resources:
        limits:
          cpus: "1"
    command: /usr/local/bin/start-workers
  rserve:
    image: localhost:5000/openstudio-rserve
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
volumes:
  osdata:
    external: true
  dbdata:
    external: true
networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
```
