### ISSUE TITLE
Simulation not running in PAT (touch issue)

### ISSUE THREAD

**Issue by IainMacdonald** [NREL/OpenStudio-server#637]
### General Issue / Feature Information

**Description**
Running models in PAT fails when using openstudio-standards. This has been 'fixed' by touching the weather file before invoking the simulation via the CLI: https://github.com/NREL/openstudio-standards/blob/a61ba54ead336dbbd5376a8b0c3f1fb139aaebaa/lib/openstudio-standards/utilities/simulation.rb#L106

**Reproduction steps:**
1. Create instance of openstudio server (v3.0.1) using the master branch of standards
2. Create a PAT model that generates an NECB prototype building
3. Run a PAT analysis - this will result in a sizing run being invoked that will use the code linked to above. 

**Actual outcome:**
Simulation does not run

**Expected outcome:**
Simulation runs!

**Other information:**

### Error on Local Server Details

**Client operating system version:**

Windows 10

**OpenStudio Server providence**

Server running locally using openstudio-server 3.0.1 and openstudio-standards nrcan_nrc branch (as this is tied to 3.0.1 just now)

**Local log files**

***From the worker container***
![image](https://user-images.githubusercontent.com/5588613/132753546-b09f1fe6-18e4-488e-9ee5-60e17235fef2.png)
This shows the file listing from the failed run. The first folder shows that all the necessary files are present but then in the run folder the in.epw file is of size zero.

***sdp_log_file from server***
```
[14:20:30.531742 ERROR] autorun sizing run failed!
/var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/autozone.rb:77:in `apply_auto_zoning'
/var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb:309:in `model_apply_standard'
/var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb:202:in `model_create_prototype_model'
/mnt/openstudio/analysis_c29b34ce-1346-4e84-bb6c-be39d4b06ef9/measures/nrc_create_necb_prototype_building/measure.rb:240:in `run'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:510:in `apply_measure'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'
:/openstudio_cli.rb:960:in `execute'
:/openstudio_cli.rb:750:in `execute'
:/openstudio_cli.rb:1744:in `
'
eval:174:in `eval'
eval:174:in `require_embedded_absolute'
eval:160:in `block in require_embedded'
eval:154:in `each'
eval:154:in `require_embedded'
eval:113:in `require'
eval:3:in `
'
[14:20:30.532055 ERROR] /var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb failed with message Runner error /var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb failed with autorun sizing run failed!, /var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/autozone.rb:77:in `apply_auto_zoning'
/var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb:309:in `model_apply_standard'
/var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb:202:in `model_create_prototype_model'
/mnt/openstudio/analysis_c29b34ce-1346-4e84-bb6c-be39d4b06ef9/measures/nrc_create_necb_prototype_building/measure.rb:240:in `run'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:510:in `apply_measure'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'
:/openstudio_cli.rb:960:in `execute'
:/openstudio_cli.rb:750:in `execute'
:/openstudio_cli.rb:1744:in `
'
eval:174:in `eval'
eval:174:in `require_embedded_absolute'
eval:160:in `block in require_embedded'
eval:154:in `each'
eval:154:in `require_embedded'
eval:113:in `require'
eval:3:in `
' in /var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:538:in `rescue in apply_measure'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:498:in `apply_measure'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'
/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'
:/openstudio_cli.rb:960:in `execute'
:/openstudio_cli.rb:750:in `execute'
:/openstudio_cli.rb:1744:in `
'
eval:174:in `eval'
eval:174:in `require_embedded_absolute'
eval:160:in `block in require_embedded'
eval:154:in `each'
eval:154:in `require_embedded'
eval:113:in `require'
eval:3:in `
'
[14:20:30.532197 ERROR] Found error in state 'os_measures' with message ["/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb failed with message Runner error /var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb failed with autorun sizing run failed!, /var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/autozone.rb:77:in `apply_auto_zoning'\n/var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb:309:in `model_apply_standard'\n/var/gems/openstudio-standards/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb:202:in `model_create_prototype_model'\n/mnt/openstudio/analysis_c29b34ce-1346-4e84-bb6c-be39d4b06ef9/measures/nrc_create_necb_prototype_building/measure.rb:240:in `run'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:510:in `apply_measure'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:960:in `execute'\n:/openstudio_cli.rb:750:in `execute'\n:/openstudio_cli.rb:1744:in `
'\neval:174:in `eval'\neval:174:in `require_embedded_absolute'\neval:160:in `block in require_embedded'\neval:154:in `each'\neval:154:in `require_embedded'\neval:113:in `require'\neval:3:in `
' in /var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:538:in `rescue in apply_measure'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:498:in `apply_measure'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:960:in `execute'\n:/openstudio_cli.rb:750:in `execute'\n:/openstudio_cli.rb:1744:in `
'\neval:174:in `eval'\neval:174:in `require_embedded_absolute'\neval:160:in `block in require_embedded'\neval:154:in `each'\neval:154:in `require_embedded'\neval:113:in `require'\neval:3:in `
':/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:647:in `rescue in apply_measure'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:305:in `apply_measure'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'\n/var/oscli/gems/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:960:in `execute'\n:/openstudio_cli.rb:750:in `execute'\n:/openstudio_cli.rb:1744:in `
'\neval:174:in `eval'\neval:174:in `require_embedded_absolute'\neval:160:in `block in require_embedded'\neval:154:in `each'\neval:154:in `require_embedded'\neval:113:in `require'\neval:3:in `
'"]} 
```
***Results of running CLI in worker container***
Running the CLI command in the worker container directly produces similar output to above. If the weather file (in.epw) is touched and the CLI command run then everything works. 

Note when it works there is no in.epw file in the run folder.

Copy of terminal showing touch working:
![image](https://user-images.githubusercontent.com/5588613/132756962-a9545e1f-bf0f-4da2-bb8d-0f1425154fbb.png)

### Docker Provisioning Error Details

**Deployment machine operating system version**

WIndows 10

**Docker version**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown
```

**Openstudio Server version / dockerhub tag used**

3.0.1

**docker-compose.yml file used**
```
# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '3.4'
services:
  db:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
  queue:
    image: redis:4.0.6
    ports:
      - "6379:6379"
  web:
    image: ${OS_SERVER_IMAGE}
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_WORKERS}
      - QUEUES=analysis_wrappers
    depends_on:
      - db
      - queue
    ports:
      - "8080:80"
    volumes:
      - osdata:/mnt/openstudio
      - osgems:/var/gems
      - ${OS_SERVER_PAT_SHARED_FOLDER}:/mnt/openstudio/server/assets/
    command: /usr/local/bin/start-server
  web-background:
    image: ${OS_SERVER_IMAGE}
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_WORKERS}
      - QUEUES=background,analyses
    depends_on:
      - db
      - queue
      - web
    volumes:
      - osdata:/mnt/openstudio
    command: /usr/local/bin/start-web-background
  worker:
    image: ${OS_SERVER_IMAGE}
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_WORKERS}
      - QUEUES=simulations
      - COUNT=1
    depends_on:
      - web
      - db
      - queue
      - rserve
    volumes:
      - osgems:/var/gems
    command: /usr/local/bin/start-workers
  rserve:
    image: ${OS_RSERVE_IMAGE}
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_WORKERS}
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
volumes:
  osdata:
  dbdata:
  osgems:
```
